---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-light-stemcell-builder}
inputs:
- name: builder-src
outputs:
- name: updated-builder-src
run:
  path: builder-src/ci/tasks/discover-aws-regions.sh
params:
  AWS_DEFAULT_REGION:    ""
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
