---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-light-stemcell-builder}

inputs:
  - name: light-stemcell
  - name: builder-src

run:
  path: builder-src/ci/tasks/publish-boshio-checksum.sh

params:
  BOSHIO_TOKEN: ""
