---
groups:
  - name: light-stemcell-builder
    jobs:
      - test-unit
      - test-drivers
      - test-integration
      - bump-minor
      - bump-major
      - promote
      - publish-centos-hvm
      - publish-centos-pv
      - publish-ubuntu-hvm
      - publish-ubuntu-pv

jobs:
  - name: test-unit
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-unit.yml

  - name: test-drivers
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-drivers.yml
        params:
          access_key:                 {{test__access_key}}
          secret_key:                 {{test__secret_key}}
          bucket_name:                {{test__bucket_name}}
          region:                     {{test__region}}
          copy_region:                {{test__copy_region}}
          ami_fixture_id:             {{test__ami_fixture_id}}
          existing_volume_id:         {{test__volume_fixture_id}}
          existing_snapshot_id:       {{test__snapshot_fixture_id}}
          uploaded_machine_image_url: {{test__machine_image_fixture_url}}

  - name: test-integration
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-integration.yml
        params:
          access_key:                 {{test__access_key}}
          secret_key:                 {{test__secret_key}}
          bucket_name:                {{test__bucket_name}}
          region:                     {{test__region}}
          copy_region:                {{test__copy_region}}
          cn_access_key:              {{test__cn_access_key}}
          cn_secret_key:              {{test__cn_secret_key}}
          cn_bucket_name:             {{test__cn_bucket_name}}
          cn_region:                  {{test__cn_region}}

  - name: promote
    plan:
      - aggregate:
        - get: builder-src
          passed: [test-unit, test-drivers, test-integration]
          resource: builder-src-in
          trigger: true
        - get: version-semver
          params: { bump: patch }
      - put: version-semver
        params: { file: version-semver/number }
      - put: builder-src-out
        params: { repository: builder-src }

  - name: publish-centos-hvm
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-out
        trigger: false
      - get: input-stemcell
        resource: centos-stemcell
        version: every
        trigger: true
      - task: build
        file: builder-src/ci/tasks/build.yml
        params:
          ami_description: {{publish__ami_description}}
          ami_virtualization_type: hvm
          ami_visibility: {{publish__ami_visibility}}
          us_ami_region: {{publish__us_region}}
          us_ami_access_key: {{publish__us_access_key}}
          us_ami_secret_key: {{publish__us_secret_key}}
          us_ami_bucket_name: {{publish__us_bucket}}
          us_ami_destinations: {{publish__us_destinations}}
          cn_ami_region: {{publish__cn_region}}
          cn_ami_access_key: {{publish__cn_access_key}}
          cn_ami_secret_key: {{publish__cn_secret_key}}
          cn_ami_bucket_name: {{publish__cn_bucket}}

      - put: light-stemcell
        params:
          from: light-stemcell/light-bosh-stemcell-(.*).tgz

  - name: publish-centos-pv
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-out
        trigger: false
      - get: input-stemcell
        resource: centos-stemcell
        version: every
        trigger: true
      - task: build
        file: builder-src/ci/tasks/build.yml
        params:
          ami_description: {{publish__ami_description}}
          ami_virtualization_type: paravirtual
          ami_visibility: {{publish__ami_visibility}}
          us_ami_region: {{publish__us_region}}
          us_ami_access_key: {{publish__us_access_key}}
          us_ami_secret_key: {{publish__us_secret_key}}
          us_ami_bucket_name: {{publish__us_bucket}}
          us_ami_destinations: {{publish__us_destinations}}
          cn_ami_region: {{publish__cn_region}}
          cn_ami_access_key: {{publish__cn_access_key}}
          cn_ami_secret_key: {{publish__cn_secret_key}}
          cn_ami_bucket_name: {{publish__cn_bucket}}

      - put: light-stemcell
        params:
          from: light-stemcell/light-bosh-stemcell-(.*).tgz

  - name: publish-ubuntu-hvm
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-out
        trigger: false
      - get: input-stemcell
        resource: ubuntu-stemcell
        version: every
        trigger: true
      - task: build
        file: builder-src/ci/tasks/build.yml
        params:
          ami_description: {{publish__ami_description}}
          ami_virtualization_type: hvm
          ami_visibility: {{publish__ami_visibility}}
          us_ami_region: {{publish__us_region}}
          us_ami_access_key: {{publish__us_access_key}}
          us_ami_secret_key: {{publish__us_secret_key}}
          us_ami_bucket_name: {{publish__us_bucket}}
          us_ami_destinations: {{publish__us_destinations}}
          cn_ami_region: {{publish__cn_region}}
          cn_ami_access_key: {{publish__cn_access_key}}
          cn_ami_secret_key: {{publish__cn_secret_key}}
          cn_ami_bucket_name: {{publish__cn_bucket}}

      - put: light-stemcell
        params:
          from: light-stemcell/light-bosh-stemcell-(.*).tgz

  - name: publish-ubuntu-pv
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-out
        trigger: false
      - get: input-stemcell
        resource: ubuntu-stemcell
        version: every
        trigger: true
      - task: build
        file: builder-src/ci/tasks/build.yml
        params:
          ami_description: {{publish__ami_description}}
          ami_virtualization_type: paravirtual
          ami_visibility: {{publish__ami_visibility}}
          us_ami_region: {{publish__us_region}}
          us_ami_access_key: {{publish__us_access_key}}
          us_ami_secret_key: {{publish__us_secret_key}}
          us_ami_bucket_name: {{publish__us_bucket}}
          us_ami_destinations: {{publish__us_destinations}}
          cn_ami_region: {{publish__cn_region}}
          cn_ami_access_key: {{publish__cn_access_key}}
          cn_ami_secret_key: {{publish__cn_secret_key}}
          cn_ami_bucket_name: {{publish__cn_bucket}}

      - put: light-stemcell
        params:
          from: light-stemcell/light-bosh-stemcell-(.*).tgz

  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: { bump: minor }
      - put: version-semver
        params: { file: version-semver/number }

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: { bump: major }
      - put: version-semver
        params: { file: version-semver/number }

resources:
  - name: builder-src-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/aws-light-stemcell-builder.git
      branch: develop
      private_key: {{builder__github_deployment_key}}

  - name: builder-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/aws-light-stemcell-builder.git
      branch: master
      private_key: {{builder__github_deployment_key}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      access_key_id: {{builder__access_key}}
      secret_access_key: {{builder__secret_key}}
      bucket: {{builder__bucket}}
      region_name: {{builder__region}}

  - name: centos-stemcell
    type: s3
    source:
      regexp: bosh-stemcell/aws/bosh-stemcell-([0-9\.]+)-aws-xen-centos-7-go_agent\.tgz
      bucket: bosh-jenkins-artifacts
      region_name: {{jenkins__region}}

  - name: ubuntu-stemcell
    type: s3
    source:
      regexp: bosh-stemcell/aws/bosh-stemcell-([0-9\.]+)-aws-xen-ubuntu-trusty-go_agent\.tgz
      bucket: bosh-jenkins-artifacts
      region_name: {{jenkins__region}}

  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-([\d\.]+)-.*\.tgz
      access_key_id: {{output__bucket_access_key}}
      secret_access_key: {{output__bucket_secret_key}}
      bucket: {{output__bucket}}
      region_name: {{output__region}}
